version: "3"

services:
  bot:
    build:
      dockerfile: docker/bot/Dockerfile
      context: .
    environment:
      SECRETS_JSON: secrets/config.json

  db:
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    ports:
      - "10001:6379"
    expose:
      - 6379
    volumes:
      - ./data/db/:/data  # snapshots

  browser:
    image: selenium/standalone-chrome:4.8.3-20230404
    shm_size: 2gb
    expose:
      - 4444
